### ISSUE TITLE
Some parameters create an error

### ISSUE THREAD

**Issue by jefcolbi** [stephane98/njembe#3]
nj command "docker-compose up --detach"

Usage: njembe command [OPTIONS] COMMAND...
Try 'njembe command --help' for help.

Error: no such option: --detach

**Comment by st9-8** [comment]
According to the last point [here](https://github.com/st9-8/njembe#useful-tips-for-njembe), if your arguments contain **--**, you must prefix the arguments part with **--**. 
In your case, type `nj command -- "docker-compose up --detach"` instead of `nj command "docker-compose up --detach"`.
